### ISSUE TITLE
Regression in Machine creation from imageName

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/machine-controller-manager-provider-openstack#48]
/kind bug
/regression
/priority 2

**What happened**:
https://github.com/gardener/machine-controller-manager-provider-openstack/pull/43 introduces a regression for Machine creation from imageName.

**What you expected to happen**:
Machine creation from imageName to work.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a MachineClass with imageName:

```yaml
providerSpec:
  apiVersion: openstack.machine.gardener.cloud/v1alpha1
  kind: MachineProviderConfig
  spec:
    imageName: <my-image>
```

2. Create a Machine

3. Make sure the machine creation fails with:

```
Cloud provider message - machine codes error: code = [Internal] message = [failed to deploy server [Name="shoot--foo--bar-baz-z1-548bb-vsg8x"]: Bad request with: [POST https://<url>/v2.1/servers], error message: {"badRequest": {"message": "Block Device Mapping is Invalid: Missing device UUID.", "code": 400}}]]
```

**Anything else we need to know**:

**Environment**:
Version: v0.8.0
